const KEY='daydreams_memories_v1';
const getMemories=()=>{try{return JSON.parse(localStorage.getItem(KEY))||[]}catch{return[]}};
const setMemories=v=>localStorage.setItem(KEY,JSON.stringify(v));
const $=s=>document.querySelector(s);
function toast(message){const t=$('#toast');if(!t)return;t.textContent=message;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),2800)}
function updateCount(){document.querySelectorAll('.archive-count').forEach(x=>{const n=getMemories().length;x.textContent=n||'';x.style.display=n?'inline':'none'})}
function niceDate(date=new Date()){return date.toLocaleDateString(undefined,{weekday:'long',month:'long',day:'numeric',year:'numeric'})}
document.addEventListener('DOMContentLoaded',()=>{updateCount();if($('#todayDate'))initJournal();if($('#camera'))initBooth();if($('#memoryGrid'))initArchive();initSound()});
function initJournal(){let mood=null,emoji='';$('#todayDate').textContent=niceDate();document.querySelectorAll('#moodOptions button').forEach(b=>b.onclick=()=>{document.querySelectorAll('#moodOptions button').forEach(x=>x.classList.remove('selected'));b.classList.add('selected');mood=b.dataset.mood;emoji=b.dataset.emoji});const diary=$('#diary');diary.oninput=()=>$('#wordCount').textContent=`${diary.value.length} / 1200`;$('#captureEntry').onclick=()=>{const song=$('#song').value.trim(),text=diary.value.trim();if(!text&&!song&&!mood){toast('Choose one little thing to remember first.');return}const memories=getMemories();memories.unshift({id:Date.now(),date:niceDate(),mood:mood||'unspoken',emoji:emoji||'✦',song,text,photo:null});setMemories(memories);updateCount();$('#captureEntry').innerHTML='<span>✓</span> Moment captured';toast('Your little moment has been tucked away.');setTimeout(()=>{$('#captureEntry').innerHTML='<span>✦</span> Capture this moment'},2400);diary.value='';$('#song').value='';$('#wordCount').textContent='0 / 1200';document.querySelectorAll('#moodOptions button').forEach(x=>x.classList.remove('selected'));mood=null;emoji=''}}
function initBooth(){let stream=null,facing='user',image=null;const video=$('#camera'),empty=$('#cameraEmpty'),cap=$('#capturePhoto');async function start(){try{if(stream)stream.getTracks().forEach(t=>t.stop());stream=await navigator.mediaDevices.getUserMedia({video:{facingMode:facing},audio:false});video.srcObject=stream;empty.style.display='none';cap.disabled=false;$('#cameraStatus').textContent='recording a little magic'}catch(e){$('#cameraStatus').textContent='camera unavailable';toast('Camera access was not available. Please allow it and try again.')}}$('#startCamera').onclick=start;$('#flipCamera').onclick=()=>{facing=facing==='user'?'environment':'user';start()};cap.onclick=()=>{if(!stream)return;const c=$('#photoCanvas');c.width=video.videoWidth;c.height=video.videoHeight;c.getContext('2d').drawImage(video,0,0);image=c.toDataURL('image/jpeg',.84);const out=$('#photoOutput');out.src=image;out.style.display='block';$('.polaroid-placeholder').style.display='none';$('#savePhoto').disabled=false;toast('Captured — the light was perfect.');};$('#clearPhoto').onclick=()=>{image=null;$('#photoOutput').style.display='none';$('.polaroid-placeholder').style.display='grid';$('#savePhoto').disabled=true};$('#savePhoto').onclick=()=>{if(!image)return;const caption=$('.polaroid-caption').textContent.trim()||'a perfect little moment';const memories=getMemories();memories.unshift({id:Date.now(),date:niceDate(),mood:'photograph',emoji:'▣',song:caption,text:'A still from a day worth keeping.',photo:image});setMemories(memories);updateCount();toast('Your polaroid is safe in the archive.');$('#savePhoto').textContent='Saved to your memories ✓';$('#savePhoto').disabled=true};window.addEventListener('beforeunload',()=>stream?.getTracks().forEach(t=>t.stop()))}
function esc(s=''){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function initArchive(){const grid=$('#memoryGrid'),empty=$('#emptyArchive'),all=getMemories();if(!all.length){empty.style.display='block';return}$('#archiveDescription').textContent=`${all.length} ${all.length===1?'moment':'moments'} held gently, ready whenever you want to revisit them.`;grid.innerHTML=all.map(m=>`<article class="memory-card ${m.photo&&!m.text?'photo-only':''}" data-id="${m.id}">${m.photo?`<img class="memory-photo" src="${m.photo}" alt="Memory from ${esc(m.date)}">`:''}<div class="memory-meta"><span>${esc(m.date)}</span><span class="memory-mood">${m.emoji}</span></div>${m.song?`<h2 class="memory-song">♫ ${esc(m.song)}</h2>`:''}${m.text?`<p class="memory-text">${esc(m.text)}</p>`:''}</article>`).join('');grid.onclick=e=>{const card=e.target.closest('.memory-card');if(!card)return;const m=all.find(x=>String(x.id)===card.dataset.id);showMemory(m)}}
function showMemory(m){const modal=$('#memoryModal');$('#modalContent').innerHTML=`<article class="modal-detail">${m.photo?`<img src="${m.photo}" alt="${esc(m.date)}">`:''}<div><span class="detail-emoji">${m.emoji}</span><p class="detail-date">${esc(m.date)} · ${esc(m.mood)}</p>${m.song?`<h2>♫ ${esc(m.song)}</h2>`:''}<p>${esc(m.text||'A small moment, kept in light.').replace(/\n/g,'<br>')}</p></div></article>`;modal.classList.add('open');modal.onclick=e=>{if(e.target===modal||e.target.closest('.modal-close'))modal.classList.remove('open')}}
function initSound(){const b=$('.sound-toggle');if(!b)return;let ctx,osc,gain;b.onclick=()=>{if(osc){osc.stop();osc=null;b.classList.remove('playing');b.innerHTML='◌ <span>ambient</span>';return}ctx=new (window.AudioContext||window.webkitAudioContext)();osc=ctx.createOscillator();gain=ctx.createGain();osc.type='sine';osc.frequency.value=174;gain.gain.value=.018;osc.connect(gain).connect(ctx.destination);osc.start();b.classList.add('playing');b.innerHTML='◉ <span>playing</span>'}}
